const experiences = [
  {
    title: "Step 1",
    company_name: "",
    // icon: starbucks,
    // iconBg: "#383E56",
    // date: "March 2020 - April 2021",
    points: ["Choose the category of service from 'our shop'"],
  },
  {
    title: "Step 2",
    company_name: "",
    // icon: tesla,
    iconBg: "#E6DEDD",
    date: "",
    points: ["Choose the type of service"],
  },
  {
    title: "Step 3",
    company_name: "",
    // icon: shopify,
    iconBg: "#383E56",
    date: "",
    points: ["Fill in the form with precise details and email address"],
  },
  {
    title: "Step 4",
    company_name: "",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "",
    points: ["Pay advance of Rs.500 via one of the payment methods available."],
  },
  {
    title: "Step 5",
    company_name: "",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "",
    points: [
      "A link for a direct chat with a designer from DZNS will be sent to the registered email address",
    ],
  },
  {
    title: "Step 6",
    company_name: "",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "",
    points: ["Chat with the designer and exchange ideas and details "],
  },
  {
    title: "Step 7",
    company_name: "",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "",
    points: ["Make the payment"],
  },
  {
    title: "Step 8",
    company_name: "",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "",
    points: ["Receive the product"],
  },
];

export { experiences };
